# Generated by Django 2.1.7 on 2019-03-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nop', models.IntegerField()),
                ('Travel_allow', models.IntegerField()),
                ('No_of_visit', models.IntegerField()),
                ('Rs_per_visit', models.IntegerField()),
                ('Research_fellow_id', models.IntegerField(choices=[(1, 'In-house'), (2, 'New'), (3, 'DNB')])),
                ('Remarks', models.TextField(blank=True)),
                ('Miscellan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital_equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Price', models.IntegerField()),
                ('Budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consum_name', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('Rs_per_unit', models.IntegerField()),
                ('Catlog_no', models.IntegerField()),
                ('Name_of_manufact', models.CharField(max_length=250)),
                ('Total3', models.IntegerField(default=9)),
                ('consum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research_fellows', models.CharField(max_length=500)),
                ('Extension_weeks', models.IntegerField()),
                ('Project_completion', models.DateField()),
                ('Reason_of_extension', models.TextField()),
                ('Detail_remaining_work', models.TextField()),
                ('Progress_report', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=250)),
                ('exist_test_id', models.IntegerField(choices=[(1, 'yes'), (2, 'no')])),
                ('No_of_pat', models.IntegerField()),
                ('Tarrif', models.IntegerField()),
                ('Total1', models.IntegerField(default=10)),
                ('invest1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.CharField(max_length=250)),
                ('exist_test_id', models.IntegerField(choices=[(1, 'yes'), (2, 'no')])),
                ('No_of_pat', models.IntegerField()),
                ('Followup', models.IntegerField()),
                ('Tarrif', models.IntegerField()),
                ('Total2', models.IntegerField(default=19)),
                ('invest2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bud_utilize', models.IntegerField()),
                ('Additional_bud', models.IntegerField()),
                ('Justify', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bud_utilize', models.IntegerField(blank=True)),
                ('Additional_bud', models.IntegerField(blank=True)),
                ('Justify', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research_fellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bud_utilize', models.IntegerField()),
                ('Additional_bud', models.IntegerField()),
                ('Justify', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaryy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Study', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Total0', models.IntegerField(default=10)),
                ('Salary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
    ]
