# Generated by Django 2.1.7 on 2019-03-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Std_details'),
        ),
    ]
