# Generated by Django 2.1.7 on 2019-03-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clinical_studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sample_sanctioned', models.IntegerField()),
                ('no_patients_screened', models.IntegerField()),
                ('no_failures', models.IntegerField()),
                ('failures_reasons', models.CharField(max_length=100)),
                ('no_patients_enrolled', models.IntegerField()),
                ('no_patients_discontinued', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='collaborations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institue', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Collab_type', models.TextField()),
                ('Ec_approval', models.BooleanField(max_length=2)),
                ('Authorship', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comp_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_study_completion', models.DateField()),
                ('budeget_status', models.BooleanField(default=True)),
                ('original_protocol_changed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='expected_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coll_date', models.DateTimeField()),
                ('data_analysis_date', models.DateTimeField()),
                ('write_up', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_improved_clin_practice', models.TextField()),
                ('any_other', models.TextField()),
                ('problems_faced', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lab_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nos_sanctioned', models.IntegerField()),
                ('nos_collected', models.IntegerField()),
                ('nos_tested', models.IntegerField()),
                ('nos_rejected', models.TextField()),
                ('new_tech_established', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Out_funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='paper_presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_level', models.CharField(choices=[(1, 'Local'), (2, 'National'), (3, 'International')], max_length=100)),
                ('conf_name', models.TextField()),
                ('Year', models.DateTimeField()),
                ('other', models.TextField()),
                ('published', models.CharField(choices=[(1, 'YES'), (2, 'NO')], max_length=100)),
                ('certificate', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='pat_sel_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define_pop', models.TextField()),
                ('In_criteria', models.TextField()),
                ('Ex_criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='prog_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_comencenment', models.DateField()),
                ('project_rate', models.TextField()),
                ('brief_summary', models.CharField(choices=[(1, 'Patients(Clinical)'), (2, 'Laboratory')], max_length=100)),
                ('provisonal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinvestigator_name', models.CharField(max_length=100)),
                ('coinvestigator_designation', models.CharField(max_length=100)),
                ('period_of_data', models.IntegerField()),
                ('enroll_period', models.IntegerField()),
                ('budget_estimate', models.IntegerField()),
                ('project_title', models.CharField(max_length=256)),
                ('appr_date_erb', models.DateField(null=True)),
                ('sample_size', models.IntegerField()),
                ('choose_fund', models.CharField(choices=[('H', 'HH'), ('O', 'Out')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project_details2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hypothesis', models.TextField()),
                ('Rationale', models.TextField()),
                ('Aim', models.TextField()),
                ('objectives', models.TextField()),
                ('Lit_review', models.TextField()),
                ('preliminary_work', models.TextField()),
                ('Research_plan', models.TextField()),
                ('conflict_of_interest', models.BooleanField(max_length=2)),
                ('conflict_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='protocol_amend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_amended', models.CharField(choices=[(1, 'YES'), (2, 'NO')], max_length=100)),
                ('comm_appr', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='study_design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_report', models.CharField(choices=[('O', 'Cohort,Prospective'), ('ER', 'Open-(non blinded)'), ('EN', 'Non-Randomized')], max_length=100)),
                ('cs_series', models.CharField(choices=[('O', 'Cohort,Retrospective'), ('ER', 'Single-blind'), ('EN', 'Study of diagnostic efficacy')], max_length=100)),
                ('srvey', models.CharField(choices=[('OC', 'Case control'), ('OS', 'Cross-sectional'), ('ERD', 'Double blind'), ('ERT', 'Triple blind')], max_length=100)),
                ('others', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='study_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informed_consent', models.CharField(choices=[('W', 'Written'), ('T', 'Telephonic'), ('V', 'Waiver'), ('O', 'Other')], max_length=100)),
                ('Intevention_code', models.CharField(choices=[('D', 'Drug Studies For approved indication'), ('O', 'Off-label use of drugs approved for other indication'), ('S', 'Surgery'), ('T', 'Special Test'), ('Q', 'Questionaire'), ('A', 'Any other')], max_length=100)),
                ('Questionaire_valid', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('Regional_lang', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('med_id', models.URLField()),
                ('surgical_id', models.URLField()),
                ('lab_id', models.URLField()),
                ('outcome_measure_id', models.TextField()),
                ('methodology', models.TextField()),
                ('proforma', models.TextField()),
                ('translation', models.TextField()),
                ('budget_id', models.CharField(max_length=100)),
                ('patient_sel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.pat_sel_id')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_coll_period', models.IntegerField()),
                ('retro_period', models.IntegerField()),
                ('patient_part', models.IntegerField()),
                ('data_analysis', models.IntegerField()),
                ('Thesis_submis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='work_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical', models.TextField()),
                ('Investigations', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='study_step',
            name='work_up_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.work_up'),
        ),
        migrations.AddField(
            model_name='project_details2',
            name='st_design_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.study_design'),
        ),
    ]
