# Generated by Django 2.1.7 on 2019-03-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('guide', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details2',
            name='studd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Std_details'),
        ),
        migrations.AddField(
            model_name='project_details2',
            name='study_steps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.study_step'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='PI_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Principal_investigator'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='Time_frame_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Time_Frame'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Std_details'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='exp_date_completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.expected_comp'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='feed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.feedback'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='lab_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.lab_study'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.paper_presentation'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='patient_clinical_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clinical_studies'),
        ),
        migrations.AddField(
            model_name='prog_report',
            name='protocol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.protocol_amend'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='clin_stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clinical_studies'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Principal_investigator'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.paper_presentation'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='protocol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.protocol_amend'),
        ),
        migrations.AddField(
            model_name='comp_report',
            name='st_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Std_details'),
        ),
    ]
