# Generated by Django 2.1.7 on 2019-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190303_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='hindu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Place_of_study', models.TextField()),
                ('Prin_invest', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('Desig', models.CharField(max_length=250)),
                ('NAme_of_research_fellow', models.CharField(max_length=250)),
                ('Invitation_paragraph', models.TextField()),
                ('Intro', models.TextField()),
                ('Why_am_i', models.TextField()),
                ('Site_details', models.TextField()),
                ('Duration', models.TextField()),
                ('How_many', models.TextField()),
                ('IS_my_part', models.TextField()),
                ('Can_i_withdraw', models.TextField()),
                ('What_will_be_done', models.TextField()),
                ('Inter_detail', models.TextField()),
                ('Follow_up', models.TextField()),
                ('allot', models.TextField()),
                ('Brief', models.TextField()),
                ('What_are_my_responsibility', models.TextField()),
                ('What_are_risk', models.TextField()),
                ('What_are_benefits', models.TextField()),
                ('Will_results', models.TextField()),
                ('Cost_participation', models.TextField()),
                ('Funding', models.TextField()),
                ('If_wrong', models.TextField()),
                ('Alt_treatment', models.TextField()),
                ('Confidentiality', models.TextField()),
                ('Study_approve', models.TextField()),
                ('Whom_contact', models.TextField()),
            ],
        ),
    ]
