# Generated by Django 2.1.7 on 2019-03-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_hindu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_details',
            name='st_any_pub',
            field=models.TextField(),
        ),
    ]
